name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_SSH_HOST }}
          username: ${{ secrets.CPANEL_SSH_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Entrar al home del usuario
            cd ~
            
            # Si el proyecto no existe, clonarlo. Si existe, actualizarlo.
            if [ ! -d "web_proto/.git" ]; then
              rm -rf web_proto
              git clone https://github.com/Ralarco/fullparnert-web.git web_proto
            else
              cd web_proto
              git pull origin main
            fi
            
            # Instalar y compilar
            cd ~/web_proto
            source ~/.bashrc # Carga nvm/node si está instalado
            npm install
            npm run build
            touch tmp/restart.txt
